language: python

# you can use a different version of Python
python: "3.8"

# don't clone more than necessary
git:
  depth: 1

# Install dependencies
install:
  - pip install -r requirements.txt

# script to run tests. Script can have many commands, one per line.
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)